using Content.Shared._Euphoria.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Euphoria.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class EuphoriaTab : Control
{
    public EuphoriaTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(EuphoriaCCVars.GreyNightVision, GreyNightVisionCheckBox);
    }
}

