# Mind Role
- type: entity
  parent: MindRoleGhostRoleFreeAgentHarmless
  id: MindRoleFoodCritic
  name: Food Critic Role
  components:
  - type: MindRole
    subtype: role-subtype-food-critic
  - type: FoodCriticRole

# Starting Gear
- type: startingGear
  id: FoodCriticGear
  equipment:
    id: VisitorPDA
    ears: ClothingHeadsetService
    #pocket1: EncryptionKeyTraffic # They do not need this IF they are not spawning on a ship.
    jumpsuit: ClothingUniformSeniorBartender
    shoes: ClothingShoesBootsLaceup
    back: ClothingBackpack

# Spawner
- type: entity
  categories: [ Spawner ]
  parent: MarkerBase
  id: SpawnPointFoodCritic
  name: ghost role spawn point
  suffix: food critic
  components:
  - type: GhostRole
    name: ghost-role-information-food-critic-name
    description: ghost-role-information-food-critic-description
    mindRoles:
    - MindRoleFoodCritic
    raffle:
      settings: default
  - type: GhostRoleCharacterSpawner
    outfitPrototype: FoodCriticGear
  - type: Sprite
    sprite: Markers/jobs.rsi
    layers:
    - state: green
    - sprite: Objects/Consumable/Food/burger.rsi

- type: entity
  categories: [ HideSpawnMenu, Spawner ]
  parent: BaseAntagSpawner
  id: SpawnPointGhostAntagFoodCritic
  components:
  - type: GhostRole
    name: ghost-role-information-food-critic-name
    description: ghost-role-information-food-critic-description
    rules: ghost-role-information-antagonist-rules
    mindRoles:
    - MindRoleFoodCritic
    raffle:
      settings: default
  - type: Sprite
    sprite: Markers/jobs.rsi
    layers:
    - state: green
    - sprite: Objects/Consumable/Food/burger.rsi
      state: icon


- type: entity
  parent: BaseGameRule
  id: AntagFoodCriticSpawn
  components:
  - type: StationEvent
    weight: 5 # DeltaV - was 6
    duration: null
    earliestStart: 30
    reoccurrenceDelay: 60 # DeltaV - was 20
    minimumPlayers: 40 # DeltaV - was 30
  - type: PrecognitionResult # DeltaV - Precogniton
    message: psionic-power-precognition-ninja-spawn-result-message
  - type: AntagRandomSpawn
  - type: GhostRoleCharacterSpawner
    outfitPrototype: FoodCriticGear
  - type: AntagObjectives
    objectives:
    #- StealResearchObjective # DeltaV: Moved to random objectives
    - DoorjackObjective
    - SpiderChargeObjective
    #- TerrorObjective # DeltaV: Moved to random objectives
    #- MassArrestObjective # DeltaV: Moved to random objectives
    - NinjaSurviveObjective
  - type: AntagRandomObjectives # DeltaV: Random objectives for hacking and killing
    sets:
    - groups: NinjaHackingObjectiveGroups
      maxPicks: 2 # only pick 2 of 3 of them to reduce metagaming
    - groups: NinjaBonusObjectiveGroups
      maxPicks: 2 # 2 kill or steal objectives max
    maxDifficulty: 100 # ignore difficulty, use maxPicks instead
  - type: AntagSelection
    agentName: ninja-round-end-agent-name
    definitions:
    - spawnerPrototype: SpawnPointGhostAntagFoodCritic
      min: 1
      max: 1
      pickPlayer: false
      #startingGear: FoodCriticGear
      #roleLoadout:
      #- RoleSurvivalSpaceNinja
      briefing:
        text: ninja-role-greeting
        color: Green
        sound: /Audio/Misc/ninja_greeting.ogg
      #components:
      mindRoles:
      - MindRoleFoodCritic
  - type: DynamicRuleCost
    cost: 75
