#+title: Civil Antagonists
#+author: SG

*Civial Antagonists: General Design Document
This is a design document for the implementation of non-disruptive,
non-destructive antagonist characters in the game Space
Station 14. These antagonists, like ones previously implemented,
have objectives that can create conflict with and among the crew
of the station. However, unlike classic atagonists, they are
not the direct and violent enemies of the crew. They are rather
external actors whose intentions are entirely peaceful and they
must be treated and handled diplomatically. This genre of
antagonist is inspired by and tailored for the unique gameplay
of one of SS14's forks, Euphoria.

*The Inspiring Issue

Euphoria, formerly known as Floof, is a fork of Space Station 14
(henceforth, SS14) and an independent server that focuses
especially on role-play over the chaos that normally defines SS14.
Due to this focus on enabling players to play out intended storylines
with their characters, and go into rounds with plans that they
don't want interrupted by catastrophic events, this game requires more
intentional control over how much chaos there is in a given
round than base SS14. That, along with consent considerations, as
players are allowed to engage in Erotic Role-Play and feel more deeply
tied to their characters, making many parts that are normally seen as
generic sci-fi concepts no-gos, significantly limits the content in
the game of Euphoria. Manual events played out by volunteer game
masters can make for exciting and highly personal events, but
there is not one happening every day, nor every hour (I would know, I
was let go from the events team for not planning any major events in my
nearly 3 months on the team. Sorry about that! Hopefully the next
batch will be more active than I was.)

The actual game that Euphoria is... is sadly relatively boring. SS14 itself is an unfinished game,
an incredible effort of nearly a decade that has yet to reach a level
of polish the volunteer developers are satisfied to call "finished"
(though with a game like this, the idea of a finish line comes more
from the culture of the video games industry where games are often
seen as being "made" and then "released" when in reality for many
games, development is continuous and infinite with no endpoint.)
Euphoria is therefore an unfinished game with core content essentially
removed. It was removed for a reason, but that void deserves to be
filled with something.

*Civil Antagonists: Something To Begin Filling That Void

The safest and most easy to implement features to begin filling the
aforementioned void of conflict/antagonists in gameplay are, in my
opinion, civil antagonists. That is, antagonists that are still very
much antagonists, as they have objectives that they wish to fulfill
that may hinder the station's crew or put them to the test in some
way, but these antagonists are civil. They arrive at the station like
any other employee or guest and they have a job to do. They could be
here to review the cuisine, or to ensure that the engineering
department is adhering to safety regulations, or anything like that.

Civil antagonists will be able to build off the strong foundation of
the in-depth technical gameplay of SS14 to incite scenarios where
players will have to deal with not just their coworkers, but
external actors who do not necessarily have the best interests of the
station at heart. Reveiwers, inspectors, advisors, emissaries, VIPs,
all manner of wacky characters will be able to test the mettle of the
various departments of the station.

This feature may also be desirable for other forks of SS14 to
implement, as it adds potential for much-needed conflict to
regularly peaceful departments such as Service and Engineering. As
such, features will be considered as part of the general
implementation vs. Euphoria-specific.

*Requirements
**General
1. They must be rollable ghost roles. These roles aren't the kind of
   roles that should be available every round. They should role every
   so often and appear as ghost roles.
2. They must have objectives, goals to spur them on. It doesn't quite
   matter how vague, or even that the goals be particular challenging.
   They just need some direction they can look to. Challenging goals
   could also be interesting.
3. They must be able to spawn at Arrivals, where regular station
   employees can spawn. They must not be crawling through the vents or
   randomly appearing in the vault.

**Euphoria-specific
1. The ghost roles must put the player's character into the role rather
  than randomly generating a character for the ghost role. Euphoria's
  players often engage deeply with their characters, and may want to
  put them in the situations allowed by these ghost roles.


*Implementation
Implementation up to date as of <2026-08-28 Fri>

**Code

***AntagLoadPlayerCharacterRule

****System
#+NAME: Antagonist Load Player Character System
#+BEGIN_SRC csharp :exports none :comments link :tangle ../../../Content.Server/_Floof/GameTicking/Rules/AntagLoadPlayerCharacterRuleSystem.cs
using Content.Server.Antag;
using Content.Server.GameTicking.Rules.Components;
using Content.Server.Preferences.Managers;
using Content.Shared.Preferences;
using Content.Server.Station.Systems;
using Content.Server.Ghost.Roles.Events;

namespace Content.Server.GameTicking.Rules;

/// <summary>
/// System that responds to AntagSelectEntityEvent, gets the player's currently selected character, spawns
/// it in the same way regular players are spawned, and sets args.Entity to the result. This is dinstinct functionality from
/// <see cref="AntagLoadProfileRuleSystem"/> in that while that system gets the appearance of the player's character,
/// this one is for when you want the whole character, name, traits, and all.
/// </summary>
public sealed class AntagLoadPlayerCharacterRuleSystem : GameRuleSystem<AntagLoadPlayerCharacterRuleComponent>
{
    [Dependency] private readonly IServerPreferencesManager _prefs = default!;
    [Dependency] private readonly IEntityManager _ent = default!;

    public override void Initialize()
    {
        base.Initialize();

        SubscribeLocalEvent<AntagLoadPlayerCharacterRuleComponent, AntagSelectEntityEvent>(OnSelectEntity);
    }

    private void OnSelectEntity(Entity<AntagLoadPlayerCharacterRuleComponent> ent, ref AntagSelectEntityEvent args)
    {
        if (args.Handled) //If something already handled this, don't handle it!
            return;

        //Get the player's selected character or, if the session is null, whatever the fuck.
        var character = args.Session != null
            ? _prefs.GetPreferences(args.Session.UserId).SelectedCharacter as HumanoidCharacterProfile
            : HumanoidCharacterProfile.RandomWithSpecies();

        //Spawn it like it was a player
        //It seems this function technically spawns the entity somewhere first,
        //but the only purpose of this system is to hand over an entity to
        //AntagSelectEntityEvent. This doesn't matter in any case, but irks me.
        var spawnedCharacter = _ent.System<StationSpawningSystem>()
            .SpawnPlayerMob(Transform(ent.Owner).Coordinates, null, character, null);

        //Create and raise this event so the character is given their traits
        var spawnedEvent = new GhostRoleSpawnerUsedEvent(ent.Owner, spawnedCharacter, character, args.Session);
        RaiseLocalEvent(spawnedCharacter, spawnedEvent, true);

        //Finally, hand over the player's character to the event raiser
        args.Entity = spawnedCharacter;
    }
}

#+END_SRC

****Component
#+NAME: Antagonist Load Player Character Component
#+BEGIN_SRC csharp :exports none :comments link :tangle ../../../Content.Server/_Floof/GameTicking/Rules/Components/AntagLoadPlayerCharacterRuleComponent.cs
namespace Content.Server.GameTicking.Rules.Components;

/// <summary>
/// Attach to an entity with <see cref="AntagSelectionComponent"/> to have it spawn the player's currently selected character.
/// </summary>
[RegisterComponent]
public sealed partial class AntagLoadPlayerCharacterRuleComponent : Component;
#+END_SRC

***AntagStationSpawnRule

****Component
#+NAME: Component that marks entities to be handled with the antagonist station spawning system.
#+BEGIN_SRC csharp :exports none :comments link :tangle ../../../Content.Server/_Floof/Antags/Components/AntagStationSpawnRuleComponent.cs
  using Robust.Shared.Map;

  namespace Content.Server.Antag.Components;

  /// <summary>
  /// Spawns this rule's antags on a station. It will attempt to
  /// obtain and return the coordinates for spawnpoints and choose one at random.
  /// Failing that, it will attempt to obtain any tile on a station.
  /// Requires <see cref="AntagSelectionComponent"/>.
  /// </summary>
  [RegisterComponent]
  public sealed partial class AntagStationSpawnRuleComponent : Component
  {
      /// <summary>
      /// Location that was picked.
      /// </summary>
      public EntityCoordinates? Coords;
  }
#+END_SRC


****System
#+NAME: System that gets the desirable station and spawn coordinates for the antagonist
#+BEGIN_SRC csharp :exports none :comments link :tangle ../../../Content.Server/_Floof/Antags/AntagStationSpawnRuleSystem.cs
  using Content.Server.Antag.Components;
  using Content.Shared.GameTicking.Components;
  using Content.Server.GameTicking.Rules;
  using Content.Server.Shuttles.Components;
  using Robust.Shared.Map;
  using Content.Server.Shuttles.Systems;
  using Content.Server.Station.Systems;
  using Content.Server.Spawners.Components;
  using Robust.Shared.Random;

  namespace Content.Server.Antag;

  public sealed class AntagStationSpawnRuleSystem : GameRuleSystem<AntagStationSpawnRuleComponent>
  {
      [Dependency] private readonly SharedTransformSystem _transform = default!;
      [Dependency] private readonly IEntityManager _ent = default!;
      [Dependency] private readonly IRobustRandom _random = default!;

      public override void Initialize()
      {
          base.Initialize();

          SubscribeLocalEvent<AntagStationSpawnRuleComponent, AntagSelectLocationEvent>(OnSelectLocation);
      }

      protected override void Added(EntityUid uid, AntagStationSpawnRuleComponent comp, GameRuleComponent gameRule, GameRuleAddedEvent args)
      {
          base.Added(uid, comp, gameRule, args);

          // we have to select this here because AntagSelectLocationEvent is raised twice because MakeAntag is called twice
          // once when a ghost role spawner is created and once when someone takes the ghost role

  	//Attempt to get the coordinates
          HandlePlayerSpawningButNotStupid(out var coords);

          comp.Coords = coords;

          if (coords is null)
          {
              if (TryFindRandomTile(out _, out _, out _, out var randomCoords))
                  comp.Coords = randomCoords;
          }
      }

      private void OnSelectLocation(Entity<AntagStationSpawnRuleComponent> ent, ref AntagSelectLocationEvent args)
      {
          if (ent.Comp.Coords != null)
              args.Coordinates.Add(_transform.ToMapCoordinates(ent.Comp.Coords.Value));
      }

      private void HandlePlayerSpawningButNotStupid(out EntityCoordinates? coords)
      {
          coords = null;

          TryGetArrivals(out var arrivals);

          if (!TryComp(arrivals, out TransformComponent? arrivalsXform))
              return;

          var mapId = arrivalsXform.MapID;

          var points = EntityQueryEnumerator<SpawnPointComponent, TransformComponent>();
          var possiblePositions = new List<EntityCoordinates>();
          while (points.MoveNext(out var uid, out var spawnPoint, out var xform))
          {
              if (spawnPoint.SpawnType != SpawnPointType.LateJoin || xform.MapID != mapId)
                  continue;

              possiblePositions.Add(xform.Coordinates);
          }

          if (possiblePositions.Count <= 0)
              return;

          coords = _random.Pick(possiblePositions);
      }

      private PlayerSpawningEvent GetSpawnEventFromHandlePlayerSpawning()
      {
          var playerSpawnEv = new PlayerSpawningEvent(default, default, default);

          _ent.System<ArrivalsSystem>().HandlePlayerSpawning(playerSpawnEv);

          return playerSpawnEv;
      }

      /// <summary>
      /// Try to get the coordinates of an entity that has <see cref="ArrivalsSourceComponent"/>,
      /// or at least any tile on a station.
      /// </summary>
      private bool TryGetAnArrivalsOrRandomTileCoords(out EntityCoordinates coords)
      {
          if (TryGetArrivals(out var arrivals))
          {
              coords = Transform(arrivals).Coordinates;
              return true;
          }

          if (TryFindRandomTile(out _, out _, out _, out coords))
              return true;

          return false;
      }

      //The method below is a carbon copy of the one of the same name in ArrivalsSystem.cs,
      //which is marked as private. I don't want to make changes to upstream files, so
      //hooray for code copying. TODO: Sort that out upstream or find a better way,
      //because this is disgusting.

      /// <summary>
      /// Try to get an entity that has <see cref="ArrivalsSourceComponent"/>
      /// </summary>
      private bool TryGetArrivals(out EntityUid uid)
      {
          var arrivalsQuery = EntityQueryEnumerator<ArrivalsSourceComponent>();

          while (arrivalsQuery.MoveNext(out uid, out _))
          {
              return true;
          }

          return false;
      }
  }
#+END_SRC

**Prototypes
The Food Critic will be used as an example of how these tools can be used.

***Food Critic
