- type: entity
  abstract: true
  id: BaseHeadDV
  components:
  - type: BodyPart # Euphoria - makes it so explosives don't blow your head off and round remove you too easily
    severThresholds:
    - types:
        Piercing: 300
    - types:
        Slash: 150
    - types:
        Blunt: 300

- type: entity
  abstract: true
  id: BaseArmDV
  components:
  - type: BodyPart
    severThresholds:
    - types:
        Piercing: 90
    - types:
        Slash: 55
    - types:
        Blunt: 90

- type: entity
  abstract: true
  id: BaseHandDV
  components:
  - type: BodyPart
    severThresholds:
    - types:
        Piercing: 90
    - types:
        Slash: 40
    - types:
        Blunt: 90

- type: entity
  abstract: true
  id: BaseLegDV
  components:
  - type: BodyPart
    severThresholds:
    - types:
        Piercing: 90
    - types:
        Slash: 80
    - types:
        Blunt: 90

- type: entity
  abstract: true
  id: BaseFootDV
  components:
  - type: BodyPart
    severThresholds:
    - types:
        Piercing: 90
    - types:
        Slash: 40
    - types:
        Blunt: 90
