- type: ropeConfiguration
  id: RopeBundle20
  parent: Leash10 # I can't be fucked to make a unique sprite
  links: 20
  linkPrototype: RopeLinkStandardRope
  dataPrototype: RopeDataStandardRope


# Link entity
- type: entity
  parent: RopeLinkBase
  id: RopeLinkStandardRope
  name: standard rope link
  categories: [ HideSpawnMenu ]


# Data entity
- type: entity
  id: RopeDataStandardRope
  parent: RopeDataBase
  name: standard rope
  categories: [ HideSpawnMenu ]
