using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Silicons.IPC;
using Content.Shared.CCVar;
using Content.Shared.NameIdentifier;
using Content.Shared.NameModifier.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.Silicons.IPC;

[GenerateTypedNameReferences]
public sealed partial class IPCMenu : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _cfgManager = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IResourceCache _cache = default!;

    public VectorFont ConsoleFont;
    private readonly NameModifierSystem _nameModifier;

    public Action? BrainButtonPressed;
    public Action? EjectBatteryButtonPressed;
    public Action<string>? NameChanged;

    public float AccumulatedTime;
    private string _lastValidName;

    public string FullText = "";
    public float CharsPerSecond = 100;

    private int _shownCharacters = 0;

    // CCVar.
    private readonly int _maxNameLength;

    public EntityUid Entity;

    public IPCMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ConsoleFont = new(_cache.GetResource<FontResource>("/Fonts/_FarHorizons/VT323/vt323-latin-400-normal.ttf"), 14);

        _nameModifier = _entity.System<NameModifierSystem>();

        _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);

        _lastValidName = NameLineEdit.Text;

        EjectBatteryButton.OnPressed += _ => EjectBatteryButtonPressed?.Invoke();
        BrainButton.OnPressed += _ => BrainButtonPressed?.Invoke();

        NameLineEdit.OnTextChanged += OnNameChanged;
        NameLineEdit.OnTextEntered += OnNameEntered;
        NameLineEdit.OnFocusExit += OnNameFocusExit;

        _entity.TryGetComponent<IPCBrainHolderComponent>(Entity, out var brainComp);
        UpdateBrainButton(brainComp);
    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
        IPCSprite.SetEntity(entity);

        if (_entity.TryGetComponent<NameIdentifierComponent>(Entity, out var nameIdentifierComponent))
        {
            NameIdentifierLabel.Visible = true;
            NameIdentifierLabel.Text = nameIdentifierComponent.FullIdentifier;

            NameLineEdit.Text = _nameModifier.GetBaseName(entity);
        }
        else
        {
            NameIdentifierLabel.Visible = false;
            NameLineEdit.Text = _entity.GetComponent<MetaDataComponent>(Entity).EntityName;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        AccumulatedTime += args.DeltaSeconds;
        IPCSprite.OverrideDirection = (Direction) ((int) AccumulatedTime % 4 * 2);

        _shownCharacters = Math.Min((int)Math.Ceiling(CharsPerSecond * AccumulatedTime), FullText.Length);
        StatusLabel.Text = FullText[.._shownCharacters];
    }

    public void UpdateState(IPCBuiState state)
    {
        _entity.TryGetComponent<IPCBrainHolderComponent>(Entity, out var brainComp);

        EjectBatteryButton.Disabled = !state.HasBattery;
        ChargeBar.Value = state.ChargePercent;
        ChargeLabel.Text = Loc.GetString("borg-ui-charge-label",
            ("charge", (int) MathF.Round(state.ChargePercent * 100)));

        FullText = PrintConsole(state, brainComp);
        StatusLabel.FontOverride = ConsoleFont;

        UpdateBrainButton(brainComp);
    }

    private static string PrintConsole(IPCBuiState state, IPCBrainHolderComponent? brain)
    {
        var separator = Loc.GetString("ipc-ui-console-separator") + '\n';

        var header = separator;
        var i = 1;
        while (true)
        {
            var index = $"ipc-ui-console-header-{i}";
            var line = Loc.GetString(index);
            if(line == index)
                break;

            header += line + '\n';
            i++;
        }
        header += separator;
        header += Loc.GetString("ipc-ui-console-diagnostics-section") + '\n';

        var itemInstalled = Loc.GetString("ipc-ui-console-part-installed");
        var itemMissing = Loc.GetString("ipc-ui-console-part-missing");

        var eyeDamageNone = Loc.GetString("ipc-ui-console-eye-damage-none");
        var eyeDamageSome = Loc.GetString("ipc-ui-console-eye-damage-some");
        var eyeDamageLots = Loc.GetString("ipc-ui-console-eye-damage-lots");

        List<(string name, string value)> status = [];
        status.Add((Loc.GetString("ipc-ui-console-status"), state.MobState.ToString()));
        status.Add((Loc.GetString("ipc-ui-console-brain"), brain != null ? itemInstalled : itemMissing));
        status.Add((Loc.GetString("ipc-ui-console-battery"), state.HasBattery ? itemInstalled : itemMissing));
        status.Add((Loc.GetString("ipc-ui-console-battery-charge"), (state.ChargePercent * 100).ToString("F2") + "%"));
        status.Add((Loc.GetString("ipc-ui-console-eye-damage"), state.EyeDamage == 0 ? eyeDamageNone : state.EyeDamage < 3 ? eyeDamageSome : eyeDamageLots));
        status.Add((Loc.GetString("ipc-ui-console-blood-level"), (state.BloodLevel * 100).ToString("F2") + "%"));

        var body = AestheticJoin(status);

        body += separator;

        var damageText = "";
        List<(string name, string value)> damage = [];
        if (state.Damage.GetTotal() > 0)
        {
            damageText += Loc.GetString("ipc-ui-console-damage-section") + '\n';
            foreach (var (name, value) in state.Damage.DamageDict.OrderByDescending(p => p.Value))
                if (value != 0)
                    damage.Add((name, value.ToString()));
        } else
            damageText += Loc.GetString("ipc-ui-console-damage-none") + '\n';

        damageText += AestheticJoin(damage);

        return header + body + damageText;
    }

    private static string AestheticJoin(List<(string name, string value)> items, char padWith = '.', string joinWith = ".....")
    {
        var result = "";

        var longestName = items.Select(p => p.name.Length).OrderDescending().FirstOrDefault(0);
        if (longestName < 1)
            return result;
        
        foreach (var (name, value) in items)
        {
            var lenDiff = longestName - name.Length;
            result += name + new string(padWith, lenDiff) + joinWith + value + '\n';
        }

        return result;
    }

    private void UpdateBrainButton(IPCBrainHolderComponent? brainComp)
    {
        if (brainComp != null && 
            brainComp.BrainEntity is EntityUid brain)
        {
            BrainButton.Text = _entity.GetComponent<MetaDataComponent>(brain).EntityName;
            BrainView.Visible = true;
            BrainView.SetEntity(brain);
            BrainButton.Disabled = false;
            BrainButton.AddStyleClass(StyleBase.ButtonOpenLeft);
        }
        else
        {
            BrainButton.Text = Loc.GetString("borg-ui-no-brain");
            BrainButton.Disabled = true;
            BrainView.Visible = false;
            BrainButton.RemoveStyleClass(StyleBase.ButtonOpenLeft);
        }
    }

    private void OnNameChanged(LineEdit.LineEditEventArgs obj)
    {
        if (obj.Text.Length == 0 ||
            string.IsNullOrWhiteSpace(obj.Text) ||
            string.IsNullOrEmpty(obj.Text))
            return;

        if (obj.Text.Length > _maxNameLength)
            obj.Control.Text = obj.Text[.._maxNameLength];

        _lastValidName = obj.Control.Text;
        obj.Control.Text = _lastValidName;
    }

    private void OnNameEntered(LineEdit.LineEditEventArgs _) => 
        NameChanged?.Invoke(_lastValidName);

    private void OnNameFocusExit(LineEdit.LineEditEventArgs obj)
    {
        if (obj.Text.Length > _maxNameLength ||
            obj.Text.Length == 0 ||
            string.IsNullOrWhiteSpace(obj.Text) ||
            string.IsNullOrEmpty(obj.Text))
        {
            obj.Control.Text = _lastValidName.Trim();
        }

        NameChanged?.Invoke(_lastValidName);
    }
}
