- type: startingGear
  id: SyndicateOperativeHostageWardenGear
  equipment:
    head: ClothingHeadHatSyndieMAA
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesNightVisionGogglesNukie # Goobstation
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterVestWeb
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: WeaponDisabler
    pocket2: WeaponPistolViperSyndicate # Euphoria
    belt: ClothingBeltMilitaryWebbingHostageWarden
  storage:
    back:
    - DeathAcidifierImplanter
    - Kanabou
