using Content.Shared._Floof.Language;
using Content.Shared._Floof.Language.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Floof.Language;

[GenerateTypedNameReferences]
public sealed partial class LanguageMenuEntry : PanelContainer
{
    public event Action? OnChosen;
    public event Action? OnMoveUp;
    public event Action? OnMoveDown;

    public readonly LanguagePrototype? Language;
    public bool CanChoose { get; private set; } = true;

    public LanguageMenuEntry(LanguagePrototype language)
    {
        Language = language;
        RobustXamlLoader.Load(this);

        NameLabel.Text = language.Name;
        DescriptionLabel.SetMessage(language.Description);

        ChatPrefixLabel.Visible = language.ChatPrefix is not null;
        if (language.ChatPrefix is {} prefix)
            ChatPrefixLabel.Text = $"chat prefix: {SharedLanguageSystem.ChatPrefixChar}{prefix}";

        ChooseButton.OnPressed += _ => OnChosen?.Invoke();
        MoveUpButton.OnPressed += _ => OnMoveUp?.Invoke();
        MoveDownButton.OnPressed += _ => OnMoveDown?.Invoke();
    }

    public void SetCanChoose(bool canChoose)
    {
        ChooseButton.Disabled = !canChoose;
        CanChoose = canChoose;
    }
}

