using Content.Client.UserInterface.Controls;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : FancyWindow
{
    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public Action? OnPrintPatientRecord; // Frontier: Allow printing hardcopy of patient information

    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        PrintRecordButton.OnPressed += (_) => OnPrintPatientRecord?.Invoke(); // Frontier

        HealthAnalyzer.Populate(msg.State);
    }
}
