# This serves as a base for all human-like inventories, adding some extra slots for underwear
- type: inventoryTemplate
  id: BaseHumanoidUnderwear
  slots:
    - name: undergarmentBottom
      slotTexture: gloves
      slotFlags: UNDERGARMENT_BOTTOM
      uiWindowPos: 3,1
      strippingWindowPos: 3,2
      displayName: Bottom Undergarment
      stripHidden: true
    - name: undergarmentTop
      slotTexture: gloves
      slotFlags: UNDERGARMENT_TOP
      uiWindowPos: 3,2
      strippingWindowPos: 3,3
      displayName: Top Undergarment
      stripHidden: true
    - name: undergarmentSocks
      slotTexture: gloves
      slotFlags: UNDERGARMENT_SOCKS
      uiWindowPos: 3,0
      strippingWindowPos: 3,1
      displayName: Socks
      stripHidden: true
