using Content.Shared._Floof.Examine;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Floof.Examine;


[GenerateTypedNameReferences]
public sealed partial class CustomExaminePresetEntry : BoxContainer
{
    public Action? OnLoadOverwrite;
    public Action? OnLoadAppend;
    public Action? OnDelete;

    public CustomExaminePresetEntry()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        LoadOverrideButton.OnPressed += _ => OnLoadOverwrite?.Invoke();
        LoadAppendButton.OnPressed +=  _ => OnLoadAppend?.Invoke();
        DeleteButton.OnPressed += _ => OnDelete?.Invoke();
    }

    public void SetPreset(CustomExaminePreset preset)
    {
        // Not sanitizing shit because this is not shared with the server/other clients
        TitleLabel.SetMessage(preset.Name);
    }
}

