using System.Linq;
using Content.Client._Floof.Scent;
using Content.Client.UserInterface.Controls;
using Content.Shared._Floof.CCVar;
using Content.Shared._Floof.Examine;
using Content.Shared._Floof.Util;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;


namespace Content.Client._Floof.Examine;


[GenerateTypedNameReferences]
public sealed partial class CustomExamineSettingsWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = null!;
    [Dependency] private readonly IConfigurationManager _cfg = null!;

    public event Action? OnReset;
    public event Action<(CustomExamineData publicData, CustomExamineData subtleData)>? OnSave;

    public List<CustomExaminePreset> Presets = new();

    public CustomExamineSettingsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ResetButton.OnPressed += _ => OnReset?.Invoke();
        SaveButton.OnPressed += _ => OnSave?.Invoke((Public.GetData(), Subtle.GetData()));
        SavePresetButton.OnPressed += _ => SaveCurrentAsPreset();
    }

    public void SetData(CustomExamineData publicData, CustomExamineData subtleData, bool force = false)
    {
        Public.SetData(publicData, force);
        Subtle.SetData(subtleData, force);
    }

    protected override void Opened()
    {
        Presets = _cfg.DecodeListFromCVar<CustomExaminePreset>(FloofCCVars.CustomExaminePresets, () => new()).ToList();
        UpdatePresetsContainer();
    }

    private void UpdatePresetsContainer()
    {
        PresetList.RemoveAllChildren();
        foreach (var preset in Presets)
        {
            var entry = new CustomExaminePresetEntry();
            entry.SetPreset(preset);
            entry.OnDelete += () =>
            {
                Presets.Remove(preset);
                UpdatePresetsContainer();
            };
            entry.OnLoadAppend += () => {  LoadPreset(preset, true); };
            entry.OnLoadOverwrite += () => { LoadPreset(preset, false); };

            PresetList.AddChild(entry);
        }
    }

    public void LoadPreset(CustomExaminePreset preset, bool append)
    {
        var newPublic = preset.PublicContent;
        var newSubtle = preset.SubtleContent;

        if (append)
        {
            if (Public.GetData().Content is { } existingPublic)
                newPublic = existingPublic + "\n" + newPublic;

            if (Subtle.GetData().Content is { } existingSubtle)
                newSubtle = existingSubtle + "\n" + newSubtle;
        }

        Public.SetData(new(newPublic, false, _timing));
        Subtle.SetData(new(newSubtle, true, _timing));
    }

    /// <summary>
    ///     Adds a preset and refreshes the UI.
    /// </summary>
    public void AddPreset(CustomExaminePreset preset, bool forceSave)
    {
        // Remove all presets that share the same name
        Presets.RemoveAll(it => it.Name.Equals(preset.Name, StringComparison.InvariantCultureIgnoreCase));
        Presets.Add(preset);
        UpdatePresetsContainer();

        if (forceSave)
            SavePresets();
    }

    private void SaveCurrentAsPreset()
    {
        var title = PresetNameField.Text.Trim();
        if (title.Length == 0)
            return;

        var preset = new CustomExaminePreset(title, Public.GetData().Content, Subtle.GetData().Content);
        AddPreset(preset, true);
    }

    private void SavePresets()
    {
        _cfg.EncodeListIntoCVar(FloofCCVars.CustomExaminePresets, Presets);
        _cfg.SaveToFile();
    }
}

