using Content.Shared._Euphoria.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Euphoria.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgeryControl : Control
{
    public Action<string>? OnButtonPressed;
    public Func<string> TooltipTextSupplier;

    private ProtoId<SurgeryActionPrototype> _surgeryId;
    private SurgerySystem _surgerySystem;

    public SurgeryControl(SurgerySystem surgerySystem, SurgeryActionPrototype surgeryActionPrototype, Func<string> tooltipTextSupplier, Control displayControl)
    {
        RobustXamlLoader.Load(this);

        _surgerySystem = surgerySystem;
        _surgeryId = surgeryActionPrototype.ID;
        TooltipTextSupplier = tooltipTextSupplier;
        SetAction(surgeryActionPrototype);
        //SetCanProduce(canProduce);
        SetDisplayControl(displayControl);

        Button.OnPressed += (_) =>
        {
            OnButtonPressed?.Invoke(_surgeryId);
        };
    }

    public void SetAction(SurgeryActionPrototype surgeryActionPrototype)
    {
        SurgeryActionName.Text = surgeryActionPrototype.ID;
        //SurgeryActionName.Text = _surgerySystem.GetSurgeryName(surgeryAction);
        _surgeryId = surgeryActionPrototype.ID;
    }

    public void SetDisplayControl(Control displayControl)
    {
        SurgeryDisplayContainer.Children.Clear();
        SurgeryDisplayContainer.AddChild(displayControl);
    }
}
