using Content.Client.UserInterface.Controls;
using Content.Shared._Euphoria.Surgery;
using Content.Shared._Euphoria.Surgery.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Euphoria.Surgery.UI;
/// <summary>
/// Client-side UI used to control a <see cref="SurgeryComponent"/>
/// Made in reference to ChemMasterWindow
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly SurgerySystem _surgery;

    public event Action<string>? SurgeryChosen;

    public List<ProtoId<SurgeryActionPrototype>> Surgeries = new();

    public SurgeryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _surgery = _entityManager.System<SurgerySystem>();

        PopulateSurgeries();
    }

    public Control GetSurgeryDisplayControl(SurgeryActionPrototype recipe)
    {
        /*if (recipe.Icon != null)
        {
            var textRect = new TextureRect();
            textRect.Texture = _spriteSystem.Frame0(recipe.Icon);
            return textRect;
        }

        if (recipe.Result is { } result)
        {
            var entProtoView = new EntityPrototypeView();
            entProtoView.SetPrototype(result);
            return entProtoView;
        }*/

        return new Control();
    }

    private string GenerateTooltipText(SurgeryActionPrototype prototype)
    {
        return "";
    }

    public void SetEntity(EntityUid uid)
    {
        var ent = uid;
        this.SetInfoFromEntity(_entityManager, ent);
    }

    public void PopulateSurgeries()
    {
        foreach (var action in Surgeries)
        {
            if (!_prototypeManager.Resolve(action, out var proto))
                continue;

            var tooltipFunction = () => GenerateTooltipText(proto);
            var control = new SurgeryControl(_surgery, proto, tooltipFunction, GetSurgeryDisplayControl(proto));
            control.OnButtonPressed += s =>
            {
                SurgeryChosen?.Invoke(s);
            };
            SurgeryActions.AddChild(control);
        }
    }
}
