using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;

namespace Content.Client._Euphoria.Surgery.UI;
/// <summary>
/// Client-side UI used to control a <see cref="SurgeryComponent"/>
/// Made in reference to ChemMasterWindow
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : FancyWindow
{
    public SurgeryWindow()
    {

    }
}
