using Content.Client.UserInterface.Controls;
using Content.Shared._Euphoria.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Euphoria.Surgery.UI;
/// <summary>
/// Client-side UI used to control a <see cref="SurgeryComponent"/>
/// Made in reference to ChemMasterWindow
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public List<ProtoId<SurgeryActionPrototype>> Surgeries = new();

    public SurgeryWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
