using Content.Shared._Euphoria.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Euphoria.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgeryControl : Control
{
    public Action<string>? OnButtonPressed;
    public Func<string> TooltipTextSupplier;

    private ProtoId<SurgeryActionPrototype> _surgeryId;
    private SurgerySystem _surgerySystem;

    public SurgeryControl(SurgerySystem surgerySystem, SurgeryActionPrototype surgeryAction, Func<string> tooltipTextSupplier, Control displayControl)
    {
        RobustXamlLoader.Load(this);

        _surgerySystem = surgerySystem;
        _surgeryId = surgeryAction.ID;
        TooltipTextSupplier = tooltipTextSupplier;
        SetAction(surgeryAction);
        //SetCanProduce(canProduce);
        SetDisplayControl(displayControl);

        Button.OnPressed += (_) =>
        {
            OnButtonPressed?.Invoke(_surgeryId);
        };
    }

    public void SetAction(SurgeryActionPrototype surgeryAction)
    {
        SurgeryActionName.Text = surgeryAction.ID;
        //SurgeryActionName.Text = _surgerySystem.GetSurgeryName(surgeryAction);
        _surgeryId = surgeryAction.ID;
    }

    public void SetDisplayControl(Control displayControl)
    {
        SurgeryDisplayContainer.Children.Clear();
        SurgeryDisplayContainer.AddChild(displayControl);
    }
}
