using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Floof.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LoadoutMetadataEditorDialog : FancyWindow
{
    public event Action<Loadout>? OnSave;

    private readonly ProtoId<LoadoutPrototype> _loadoutProto;
    private readonly ProtoId<LoadoutGroupPrototype> _groupProto;
    private Loadout _loadout;

    public LoadoutMetadataEditorDialog(Loadout currentState, ProtoId<LoadoutPrototype> loadoutProto, ProtoId<LoadoutGroupPrototype> groupProto)
    {
        _loadoutProto = loadoutProto;
        _groupProto = groupProto;
        RobustXamlLoader.Load(this);

        // We maintain a copy of the original loadout to avoid polluting the character profile in the event the user decides not to save the loadout
        _loadout = new Loadout(currentState);
        Load(_loadout);

        CancelButton.OnPressed += _ => Close();
        SaveButton.OnPressed += _ =>
        {
            Save();
            Close();
        };

    }

    public void Load(Loadout currentState)
    {
        CustomNameField.Text = currentState.NameOverride is { Length: >0 } nameOverride ? nameOverride : string.Empty;
        CustomDescField.Text = currentState.DescriptionOverride is { Length: >0 } descOverride ? descOverride : string.Empty;

        CustomColorEnabled.Pressed = currentState.ColorOverride != null;
        ColorSelector.Color = currentState.ColorOverride is { Length: > 0 } customColor
            ? Color.FromHex(customColor, Color.White)
            : Color.White;
    }

    public void Save()
    {
        // Sanitize data: empty text fields means no override, disabled color tint means no color tint
        string? customName = CustomNameField.Text.Trim();
        string? customDesc = CustomDescField.Text.Trim();
        Color? customColor = CustomColorEnabled.Pressed ? ColorSelector.Color : null;

        if (customName.Length == 0)
            customName = null;
        if (customDesc.Length == 0)
            customDesc = null;
        // Ideally this should be done server-side but w/e, this is just to prevent players from hurting each other's eyes by making completely black items
        if (customColor != null)
        {
            var colorHsl = Color.ToHsl(customColor.Value);
            if (colorHsl.Z < 0.1f)
                customColor = Color.FromHsl(colorHsl + new Vector4(0, 0, 0.1f, 0));
        }

        _loadout.NameOverride = customName;
        _loadout.DescriptionOverride = customDesc;
        _loadout.ColorOverride = customColor?.ToHexNoAlpha();

        OnSave?.Invoke(_loadout);
    }
}
